site_name: ESA AI Docs
site_description: 'ESA AI Docs'
# Repository

repo_name: 'ai-extensions/docs'
repo_url: 'https://github.com/ai-extensions/docs'
edit_uri: 'blob/main/docs/src/'
#site_url: 'https://github.io/ai-docs'


theme:
  name: material

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - attr_list

plugins:
  - search
  - mkdocs-jupyter

nav:
  - Welcome to ESA AI-Extensions App Hub:
    - intro/foreword.md
    - intro/registration.md
  - App Hub Core Services:
    - core/jupyterhub.md
    - core/qgis.md
    - core/stac.md
  - Solutions hosted on JupyterHub:
    - solutions/jupyterlab.md
    - solutions/codeserver.md
    - solutions/mlflow.md
    
  - Introduction: 'index.md'