site_name: ESA AI-Extensions App Hub User Manual
site_description: 'ESA AI-Extensions App Hub User Manual'
# Repository

repo_name: 'ai-extensions/docs'
repo_url: 'https://github.com/ai-extensions/docs'
edit_uri: 'blob/main/docs/src/'
#site_url: 'https://github.io/ai-docs'

theme:
  name: material

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - attr_list

plugins:
  - search
  - mkdocs-jupyter

nav:
  - Overview: 'index.md'
  - AI-Extensions:
    - intro/foreword.md
    - intro/registration.md
  - ML-Lab:
    - core/jupyterlab.md
    - core/codeserver.md
    - core/mlflow.md
    - core/aws.md
  - Additional Apps:
    - plus/jupyterhub.md
    - plus/qgis.md
    - plus/stac.md
  - User Scenarios:
    - scenarios/scenario1.md
    - scenarios/scenario2.md
    - scenarios/scenario3.md
    - scenarios/scenario4.md
    - scenarios/scenario5.md
    - scenarios/scenario6.md
    - scenarios/scenario7.md
    - scenarios/scenario8.md
    - scenarios/scenario9.md
    - scenarios/scenario10.md