site_name: ESA AI-Extensions App Hub User Manual
site_description: 'ESA AI-Extensions App Hub User Manual'
# Repository

repo_name: 'ai-extensions/docs'
repo_url: 'https://github.com/ai-extensions/docs'
edit_uri: 'blob/main/docs/src/'
#site_url: 'https://github.io/ai-docs'

theme:
  name: material

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - attr_list

plugins:
  - search
  - mkdocs-jupyter

nav:
  - ESA AI-Extensions App Hub:
    - intro/foreword.md
    - intro/registration.md
  - App Hub Core Services:
    - core/jupyterhub.md
    - core/qgis.md
    - core/stac.md
  - Solutions hosted on JupyterHub:
    - solutions/jupyterlab.md
    - solutions/codeserver.md
    - solutions/mlflow.md
    - solutions/aws.md
  - Archive: 'index_old.md'