site_name: ESA AI Docs
site_description: 'ESA AI Docs'
# Repository

repo_name: 'ai-extensions/docs'
repo_url: 'https://github.com/ai-extensions/docs'
edit_uri: 'blob/main/docs/src/'
#site_url: 'https://github.io/ai-docs'


theme:
  name: material

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - attr_list

plugins:
  - search
  - mkdocs-jupyter

nav:
  - Introduction: 'index.md'
  - Configuration: 'configuration-example.md'
  - JupyterHub API: 'jupyterhub-api-example.md'
